/*********************************************************************
 * Name:      	main.h
 * Purpose:   	Declares simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:   	wxWidgets license (www.wxwidgets.org)
 *
 * Notes:		Note that all GUI creation code is declared in
 * 				gui.h source file which is generated by wxFormBuilder.
 *********************************************************************/

#ifndef __main__
#define __main__

// main wxWidgets header file
#include <wx/wx.h>

#include "ocpn_plugin.h"

#include "gui.h"
#include "ncdf_reader.h"
#include "wx/wfstream.h"
#include <wx/datetime.h>
#include <vector>
#include <wx/dirdlg.h>

#include <stdio.h> 
#include <stdlib.h>
#include <netcdf.h>

/* We are reading 3D data, a 48 x 70 x 140 time-lat-lon grid. */
#define NDIMS 3
#define NTIME 48	
#define NLAT 70	
#define NLON 140

#define LAT_NAME "latitude"
#define LON_NAME "longitude"
#define TIME_NAME "time"
#define V_NAME "v"
#define U_NAME "u"

#define ERR(e) { printf("Error: %s\n", nc_strerror(e)); return 2; }

using namespace std;


////////////////////////////////////////////////////////////////////////////////
// main application frame declaration
////////////////////////////////////////////////////////////////////////////////
#ifndef PI
#define PI        3.1415926535897931160E0      /* pi */
#endif

struct treeItems
{
	long startDate;
	int stepRange[48];
	int numberOfItems;
	wxDateTime dateTimes[96];
	int stepTimes[96];
	int messageCount;
};

struct Selection
{
    wxDouble topLat;
    wxDouble topLon;
    wxDouble bottomLat;
    wxDouble bottomLon;
};

class ncdf_pi;
class ncdfDataMessage;

class MainDialog : public ncdfDialog {
public:
	MainDialog( wxWindow *parent );
	virtual ~MainDialog();
	
	ncdfReader 	*my_ncdfReader;
	
	void SetCursorLatLon(double lat, double lon);
	void setPlugIn(ncdf_pi *p);
	
	ncdf_pi	*pPlugIn;
	wxWindow	*m_parent;
	Selection	selectionRectangle;
	double		m_cursor_lon, m_cursor_lat;
	double *my_ucurr = 0;
	double *my_vcurr = 0;
	int treeMinutes[96];

	double** gridu;
	double** gridv;

	
	ncdfDataMessage myncdfData, myData, myMessage;
	vector<ncdfDataMessage> myDataVector;
	int ncdf_get_data(wxString filestr);
	int MainDialog::ncdf_get_keys(wxString filestr);
	int MainDialog::nc_get(wxString filestr);

	int ncdf_get_ncdf1();
	double** makeGridDataCURRENT(ncdfDataMessage message, wxString current);
	int np;

private:
	void UpdateTrackingControls();
	void printCurrentData();
	
	wxString toBeaufort(wxFloat32 w);
	wxLogWindow *log_window_m;

	

protected:
	// protected event handlers
	virtual void OnCloseFrame( wxCloseEvent& event );
	virtual void onCloseDialog( wxCloseEvent& event );
	virtual void OnExitClick( wxCommandEvent& event );
	virtual void onFileButtonClick(wxCommandEvent& event);

	wxDateTime GetDateFromHours(int hours_in);

	virtual void onDirChanged(wxCommandEvent& event);
	virtual void onTreeSelectionChanged(wxTreeEvent& event);
	virtual void onTreeItemRightClick(wxTreeEvent& event);
	virtual void onDCurrentClick( wxCommandEvent& event );
	virtual void onBmpCurrentForceClick( wxCommandEvent& event );
	void fillDirTree(wxString dir, bool start, wxTreeItemId id);
	void addChildren(wxTreeItemId id, wxString s);
};

class MyTreeItemData : public wxTreeItemData
{
public:
	MyTreeItemData(wxDateTime *dt, wxUint32 hour, ncdfDataMessage *myData, wxString *myFile);
	
	wxString myFile;
	ncdfDataMessage myData;
	wxUint32 hour;
	wxDateTime dt;
};

#endif //__main__
